_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 4001697a-ad91-4803-9966-6e1a1e5a7fa2
name: Yamindustries
mail: webmaster@yamindustries.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
